### ISSUE TITLE
 Compiling New dbx4fb.dll 

### ISSUE THREAD

**Issue by moyzer** [ccy/dbx4fb#6]
Hello Chee Yang Chau,
Thank you very much for your great work :))
I would like to compile the new dbx4fb.dll  with Delphi 10.4.2 but have somme difficulties to setup the two libraries you suggest :
1.  jedi-apilib
2. delphi-firebird-api
Can you please describe step by step their installation on Delphi 10.4.2, 
**or could you simply, if you have time (i know you are very buzy)  compile it (last dbx4fb.dll )  for us and upload it somewhere**

Many Thx
______________
M.-Y Zerrouki
my email :  contact@abaksoft.net

**Comment by moyzer** [comment]
**Done.**
But with a hard day.

**Description Problem :** 
When building the JediAPI_Dynamic Delphi 10.4.2 detect many errors :
 


**Here is a Step by Step Building  dbx4fb.dll**

**A. Download**

1. dbx4fb-master.zip
2. delphi-firebird-api-master.zip
3. jedi-apilib-revise.zip
4. DelphiZip-master.zip



**B.  Add Paths to  the Delphi Library :**  

1.  windows32  and Windows64
...\DelphiZip-master\DelphiZip-master

2.  windows32  and Windows64
...\jedi-apilib-revise\jedi-apilib-revise\jsetup\trunk\source

3.  windows32  and Windows64
...\jedi-apilib-revise\jedi-apilib-revise\jwapi\trunk\Win32API

4.  windows32  and Windows64
...\jedi-apilib-revise\jedi-apilib-revise\jwscl\trunk\source

5.  windows32  and Windows64
...\delphi-firebird-api-master\delphi-firebird-api-master\source

6.  windows32  and Windows64
...\dbx4fb-master\dbx4fb-master\source



**C. Install ZipMaster Component  :**
1.  Open, Compile and Build 
...\DelphiZip-master\DelphiZip-master\Packages\Tokyo\ZipMaster.groupproj
 and Install   \ZipMasterD25.bpl   (Right Click >  Install)


**D.  Open** 
...\jedi-apilib-revise\jedi-apilib-revise\jwapi\trunk\Packages\bds27\_PackageProjectGroup_Delphi.groupproj

1. Check Syntaxe  and Replace all Old uses by

WinApi.Windows
Winapi.Windows.TColorRef
Winapi.ActiveX
Winapi.CommCtrl
WinApi.msxml
System.SysUtils
Winapi.ActiveX.IServiceProvider
System.Variants
System.Win.ComObj
System.DateUtils
VCL.OleServer
VCL.OleCtrls
System.Classes
Vcl.Graphics
System.Win.StdVCL



2. Don'nt Right Click on Compile All bpl (Top level), but compile one by one (Right Click).  
Windows32 and Windows 64   (Debug)


3. Right Click on   JediApi_SingleUnits.bpl  and Install it

4. Replace Name :  JediApi_DynamicDebug   by   JediApi_Dynamic
On ...\jedi-apilib-revise\jedi-apilib-revise\jwapi\trunk\Packages\bds27\bin\debug\dynamic_Win64\

**Imporant** :
This problem appears only for win64 and prevent the detection Path library.



**E.  Open, Compile and Build** 
...\delphi-firebird-api-master\delphi-firebird-api-master\project\DFirebirdAPI.dproj
Windows 32  and Windows 64 (Debug)


**F.  Open**
...\dbx4fb-master\dbx4fb-master\project\Default.groupproj

1. Compile and Build : 
   dbx4fbrt270.bpl
   Windows 32  and Windows 64 (Release)

2. Compile and Build : (Extend Tree  dbx4fb.dll)
   dbx4fb.dll
   Windows 32  and Windows 64 (Release)




**G.  Finally you get it :**

dbx4fb.dll  for Windows 32 :
...\dbx4fb-master\dbx4fb-master\project\Win32\Release\dbx4fb.dll

dbx4fb.dll  for Windows 64 :
...\dbx4fb-master\dbx4fb-master\project\Win64\Release\dbx4fb.dll



__________
For those who have difficulties to compile it here is it  (Build Release with Delphi 10.4.2 ) :

**dbx4fb.dll**
MD5 
dbx4fb_32.zip  :  29d880cfd9cbf0ea2b7276ffe5fb2242
dbx4fb_64.zip  :  8d030b7e71c7d7a04423828ea2e98085

[dbx4fb_32.zip](https://github.com/ccy/dbx4fb/files/7246618/dbx4fb_32.zip)
[dbx4fb_64.zip](https://github.com/ccy/dbx4fb/files/7246634/dbx4fb_64.zip)


_____________
Best Regards
M.-Y ZERROUKI

**Comment by jvtecheto** [comment]
Many thanks friend, awesome work

**Comment by moyzer** [comment]
Hello,
I would like first, to thanks Mr. Chee Yang Chau for his upgrade to FB 4.

So, i compiled the dll with Delphi Alexandria 11 Update 1 :
Have fun :)

**A. Download :**
1. dbx4fb-master.zip
2. delphi-firebird-api-master.zip
3. jedi-apilib-revise.zip
4. DelphiZip-master.zip
5. delphi-int128-master.zip  (for Delphi 11.1)



**B.  Add Paths to  the Delphi Library :**  

1.  windows32  and  Windows64
...\DelphiZip-master\DelphiZip-master

2.  windows32  and  Windows64
...\jedi-apilib-revise\jedi-apilib-revise\jsetup\trunk\source

3.  windows32  and  Windows64
...\jedi-apilib-revise\jedi-apilib-revise\jwapi\trunk\Win32API

4.  windows32  and  Windows64
...\jedi-apilib-revise\jedi-apilib-revise\jwscl\trunk\source

5.  windows32  and  Windows64
...\delphi-firebird-api-master\delphi-firebird-api-master\source

6.  windows32  and  Windows64
...\dbx4fb-master\dbx4fb-master\source


7. Windows32
...\jedi-apilib-revise\jedi-apilib-revise\jwapi\trunk\Packages\bds28\bin\release\dynamic_Win32

8. Windows 64
...\jedi-apilib-revise\jedi-apilib-revise\jwapi\trunk\Packages\bds28\bin\release\dynamic_Win64

9. Windows32
...\delphi-firebird-api-master\delphi-firebird-api-master\project\Win32\Release

10. Windows64
...\delphi-firebird-api-master\delphi-firebird-api-master\project\Win64\Release


11.Windows32
...\delphi-int128-master\delphi-int128-master\Win32\Release

12.Windows64
...\delphi-int128-master\delphi-int128-master\Win64\Release






**C. Install ZipMaster Component  :**
1.  Open, Compile and Build 
...\DelphiZip-master\DelphiZip-master\Packages\Tokyo\ZipMaster.groupproj
 and Install   \ZipMasterD25.bpl   (Right Click >  Install)


**D.  Open** 
...\jedi-apilib-revise\jedi-apilib-revise\jwapi\trunk\Packages\bds28\_PackageProjectGroup_Delphi.groupproj


1. Don'nt Right Click on Compile All bpl (Top level), but compile one by one (Right Click).  
Windows32 and  Windows 64   (Release)

2. Right Click  on   JediApi_SingleUnits.bpl  and  Install it

3. Replace :  JediApi_DynamicRelease   by   JediApi_Dynamic
On ...\jedi-apilib-revise\jedi-apilib-revise\jwapi\trunk\Packages\bds28\bin\debug\dynamic_Win64\
 
Same with : JediApi_StaticRelease -->  JediApi_Static




**E.  Open, Compile and Build** 
...\delphi-firebird-api-master\delphi-firebird-api-master\project\DFirebirdAPI.dproj
Windows 32  and  Windows 64 (Release)


**F.  Open**
...\dbx4fb-master\dbx4fb-master\project\Default.groupproj

1. Compile and Build : 
   dbx4fbrt270.bpl
   Windows 32  and Windows 64 (Release)

2. Compile and Build : (Extend Tree  dbx4fb.dll)
   dbx4fb.dll
   Windows 32  and Windows 64 (Release)




**F.  Finally you get it :**

dbx4fb.dll  for Windows 32 :
...\dbx4fb-master\dbx4fb-master\project\Win32\Release\dbx4fb.dll

dbx4fb.dll  for Windows 64 :
...\dbx4fb-master\dbx4fb-master\project\Win64\Release\dbx4fb.dll

________________
**MD5 / 32 :**  630e6431c2289955ca3d9e81712d647b
**MD5 /64 :**   b6072b8ee1922211836799e23e10c57c
[dbx4fb_D11_1_64.zip](https://github.com/ccy/dbx4fb/files/8404722/dbx4fb_D11_1_64.zip)
[dbx4fb_D11_1_32.zip](https://github.com/ccy/dbx4fb/files/8404723/dbx4fb_D11_1_32.zip)

Best Regards
M.-Y ZERROUKI

**Comment by oliwe** [comment]
Thank you for the work - I use the win64 dbx4fb.dll - no problems so far :-)

**Comment by ccy** [comment]
A pre-compiled release binaries for both Win32 and Win64 is ready.
