### ISSUE TITLE
The new dbx4fb.dll  with Delphi Alexandria 11.2  not work ?

### ISSUE THREAD

**Issue by moyzer** [ccy/dbx4fb#7]
Hi Chee Yang Chau,
I just tested the new attached dbx4fb.dll  (whith Delphi 11.2)-->   DBXError  not implemented.

![1](https://user-images.githubusercontent.com/22027558/216410021-f0ab39c8-d84d-4026-8a5a-2c7b038729f5.png)

I downloaded all the projects, Compiled them on Delphi 11.2,
as usually, but same problem.

Can you please check.
Thx

**Comment by moyzer** [comment]
For the test :

I am using a  DBExpress connection, adapted  from :
https://www.idefixpack.de/blog/2010/11/dbx-without-deploying-dbxdrivers-ini/

**Comment by moyzer** [comment]
[Unit_dbxdriver.txt](https://github.com/ccy/dbx4fb/files/10572194/Unit_dbxdriver.txt)

**Comment by ccy** [comment]
Can you try with latest commits?

**Comment by moyzer** [comment]
Unfortunately gives the same error : "DBX Error :  Not implemented"
- Compiled on 14/04/2023  
- With Last Delphi 11.3
- With the last commits.

Maybe the problem is on the new Delphi release 11.3 

I sent you a testCase.
[Prg.zip](https://github.com/ccy/dbx4fb/files/11233095/Prg.zip)

**Comment by ccy** [comment]
The `dbx4fb.dll` driver will not support `TDBXDynalinkDriverNative` based drivers.

Try remove your `DBXFireBird.pas` driver and use RAD Studio native `Data.DbxFirebird` driver with the following changes:

```delphi
uses Data.DbxFirebird, Data.SqlExpr;

procedure TForm3.Button1Click(Sender: TObject);
var C: TSQLConnection;
    CheminBase,
    LibraryName, VendorLib:string;
begin
  CheminBase:=ExtractFilePath(Application.ExeName) + 'Data\Base.fdb';
  LibraryName:=ExtractFilePath(Application.ExeName) + 'Data\dbx4fb.dll';
  VendorLib:='C:\Program Files (x86)\Firebird\Firebird_2_5\bin\fbclient.dll';

  //=================================
  C := TSQLConnection.Create(Self);

//  C.DriverName := 'FireBirdConnection';
//  C.LibraryName :=LibraryName;
//  C.VendorLib :=VendorLib;
  C.DriverName := 'Firebird';    // use DriverName defined in Data.DbxFirebird.pas

  C.GetDriverFunc := 'getSQLDriverFIREBIRD';

  C.Params.Clear;
  C.Params.Add('User_Name=SYSDBA');
  C.Params.Add('Password=masterkey');
  C.Params.Add('Database=' + CheminBase);
  C.Params.Add('LibraryName=' + LibraryName);  // Specify LibraryName here
  C.Params.Add('VendorLib=' + VendorLib);  // Specify VendorLib here
  C.Open;
  //=================================
  if C.Connected then
   showmessage('OK')
  else
   beep;
end;
```

**Comment by moyzer** [comment]
My Delphi 11.3 **Professional**, don'nt recognize the   **uses Data.DbxFirebird** 
Where can I get it ?
Thx.


**On C:\Program Files (x86)\Embarcadero\Studio\22.0\source\data\dbx
There is no  Data.DBXFirebird.pas**

![1](https://user-images.githubusercontent.com/22027558/232294657-24365b27-30f5-46f1-bf36-fcb9ceb2439f.png)
![2](https://user-images.githubusercontent.com/22027558/232297441-209dd0f9-70f7-4e12-93fc-cb75169bfb70.png)

**Comment by oliwe** [comment]
Hello, I've been using the dbx4fb for a long time. Thank you very much for that!
The last version that works for me is 4.1.2022.58. 
With the versions from 4.1.2022.59 onwards, I could no longer connect to a database.
I have never investigated this in depth, so I am still on 4.1.2022.58.
At the moment I'm working with RAD Studio 11.3 (compiling for Win64 using C++).
The problem was already with RAD Studio 11.2 and 11.1.5.

**Comment by ccy** [comment]
> My Delphi 11.3 **Professional**, don'nt recognize the **uses Data.DbxFirebird** Where can I get it ? Thx.
> 
> **On C:\Program Files (x86)\Embarcadero\Studio\22.0\source\data\dbx There is no Data.DBXFirebird.pas**
> 
> ![1](https://user-images.githubusercontent.com/22027558/232294657-24365b27-30f5-46f1-bf36-fcb9ceb2439f.png) ![2](https://user-images.githubusercontent.com/22027558/232297441-209dd0f9-70f7-4e12-93fc-cb75169bfb70.png)

Is there `Data.DbxFirebird.dcu` in the RAD Studio folder?  I am not quite sure if it is only available in Enterprise version and beyond.

**Comment by ccy** [comment]
> Hello, I've been using the dbx4fb for a long time. Thank you very much for that! The last version that works for me is 4.1.2022.58. With the versions from 4.1.2022.59 onwards, I could no longer connect to a database. I have never investigated this in depth, so I am still on 4.1.2022.58. At the moment I'm working with RAD Studio 11.3 (compiling for Win64 using C++). The problem was already with RAD Studio 11.2 and 11.1.5.

Is the current build: [4.1.2023.62](https://github.com/ccy/dbx4fb/releases/tag/4.1.2023.62) works for you?

**Comment by oliwe** [comment]
no - .59, .60, .61 and .62 do not work for me.

I have Data.DbxFirebird.dcu (in C:\Program Files (x86)\Embarcadero\Studio\22.0\lib\win64\release and win64\debug and win32\release and win32\debug) and Data.DbxFirebird.pas (in C:\Program Files (x86)\Embarcadero\Studio\22.0\source\data\dbx) in my RAD Studio Folder (Enterprise Version).

**Comment by moyzer** [comment]
Hello Chee Yang Chau,

> Is there `Data.DbxFirebird.dcu` in the RAD Studio folder? I am not quite sure if it is only available in Enterprise version and beyond.

No, infortunately, Data.DbxFirebird .dcu  and  .pas  is completely absent  in the current Delphi **Professional** 11.3  
It seems that EMB deleted it definitively.

But, when I tested the same code you advise, with :
 
[Prg_DBXInterBase.zip](https://github.com/ccy/dbx4fb/files/11250351/Prg_DBXInterBase.zip)

`  C.DriverName := 'Interbase';`
`  C.GetDriverFunc := 'getSQLDriverInterbase';`

Then it connect  (with dbx4fb.dll  your last commits)

The Question, now is :  can we use this dbx4fb.dll  on Interbase Driver with FireBird 2.5 ?  
No problem with Transactions ?

Thx...

**Comment by oliwe** [comment]
I just tested version 4.1.2023.62 in debug mode (RAD Studio 11.3, C++, Win64). 
I get: 
<img width="445" alt="dbx4fb_dll_error" src="https://user-images.githubusercontent.com/85241822/232534244-bdb738d9-5ec7-4612-97cb-6c7ccab337e4.png">

**Comment by ccy** [comment]
> I just tested version 4.1.2023.62 in debug mode (RAD Studio 11.3, C++, Win64). I get: <img alt="dbx4fb_dll_error" width="445" src="https://user-images.githubusercontent.com/85241822/232534244-bdb738d9-5ec7-4612-97cb-6c7ccab337e4.png">

Can you try this: https://github.com/ccy/dbx4fb/issues/7#issuecomment-1509474486

**Comment by ccy** [comment]
> Hello Chee Yang Chau,
> 
> > Is there `Data.DbxFirebird.dcu` in the RAD Studio folder? I am not quite sure if it is only available in Enterprise version and beyond.
> 
> No, infortunately, Data.DbxFirebird .dcu and .pas is completely absent in the current Delphi **Professional** 11.3 It seems that EMB deleted it definitively.
> 
> But, when I tested the same code you advise, with :
> 
> [Prg_DBXInterBase.zip](https://github.com/ccy/dbx4fb/files/11250351/Prg_DBXInterBase.zip)
> 
> ` C.DriverName := 'Interbase';` ` C.GetDriverFunc := 'getSQLDriverInterbase';`
> 
> Then it connect (with dbx4fb.dll your last commits)
> 
> The Question, now is : can we use this dbx4fb.dll on Interbase Driver with FireBird 2.5 ? No problem with Transactions ?
> 
> Thx...

Yes, You can use `dbx4fb.dll` for Firebird 2.5.  You can find the list of of firebird distribution I perform the test [here](../tree/master/source/testcase/dbxfbTests.ini)

**Comment by moyzer** [comment]
> Yes, You can use `dbx4fb.dll` for Firebird 2.5. 

Thank you Chee Yang Chau,
And sorry if i take your time.

I reformulate my question :
• Is it safe to go with  "interbase" :

C.DriverName := 'Interbase';  C.GetDriverFunc := 'getSQLDriverInterbase

Instead of "Firebird" ?

• No problem in compatibility ?
• No problem with  Transactions ?

If it can be problem, i will stay with an old dbx4fb.dll  version  in production with my Delphi 11.3 Pro.

Thx.

**Comment by ccy** [comment]
@moyzer . I can't be sure about this: `Is it safe to go with "interbase"`

However, you may try run the testcases with the interbase settings you want and see if it fit to your needs.

**Comment by moyzer** [comment]
> @moyzer . I can't be sure about this: `Is it safe to go with "interbase"`
> 
> However, you may try run the testcases with the interbase settings you want and see if it fit to your needs.

Big Thx :)
Best wishes...

**Comment by oliwe** [comment]
> > I just tested version 4.1.2023.62 in debug mode (RAD Studio 11.3, C++, Win64). I get: <img alt="dbx4fb_dll_error" width="445" src="https://user-images.githubusercontent.com/85241822/232534244-bdb738d9-5ec7-4612-97cb-6c7ccab337e4.png">
> 
> Can you try this: [#7 (comment)](https://github.com/ccy/dbx4fb/issues/7#issuecomment-1509474486)

No - does not work for me. 
4.1.2022.58 works - if I replace it with 4.1.2022.62 I get still the mentioned error.

I am using fbclient.dll version 3.0.10.33601.

(Sorry for late reply)

**Comment by oliwe** [comment]
Hello Chee Yang Chau,

 �

No - does not work for me.

4.1.2022.58 works - if I replace it with 4.1.2022.62 I get still the mentioned error.

 �

I am using fbclient.dll version 3.0.10.33601.

 �

(Sorry for late reply)

 �

Kind regards,

Oliver Weinheimer

 �
